### ISSUE TITLE
:354: field visible_for undefined in record acl_props error

### ISSUE THREAD

**Issue by caiodark** [zotonic/mod_acl_simple_roles#1]
I cloned the project, i do z:m() from zotonic console or make from zotonic dir. I get these errors:
`Recompile: /home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles
/home/zotonic/zotonic/user/modules/mod_acl_adminonly/mod_acl_adminonly.erl:70: undefined macro 'ACL_VIS_PUBLIC'
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:84: undefined macro 'ACL_VIS_PUBLIC'
/home/zotonic/zotonic/user/modules/mod_acl_adminonly/mod_acl_adminonly.erl:98: undefined macro 'ACL_VIS_PUBLIC'
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:126: undefined macro 'ACL_VIS_USER'
/home/zotonic/zotonic/user/modules/mod_acl_adminonly/mod_acl_adminonly.erl:30: function observe_acl_can_see/2 undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:144: undefined macro 'ACL_VIS_PUBLIC'
/home/zotonic/zotonic/user/modules/mod_acl_adminonly/mod_acl_adminonly.erl:30: function observe_acl_rsc_update_check/3 undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:32: function observe_acl_can_see/2 undefined
/home/zotonic/zotonic/user/modules/mod_acl_adminonly/mod_acl_adminonly.erl:50: field visible_for undefined in record acl_props
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:98: record acl_rsc_update_check undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:100: record acl_rsc_update_check undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:105: function constrain_visible_for/3 undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:110: record acl_rsc_update_check undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:111: variable 'Id' is unbound
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:111: function constrain_visible_for/3 undefined
/home/zotonic/zotonic/user/modules/mod_acl_simple_roles/mod_acl_simple_roles.erl:354: field visible_for undefined in record acl_props
GNUmakefile:30: recipe for target 'compile' failed
`

**Comment by ddeboer** [comment]
Which Zotonic version are you running?

The obsolete visibility flag (including the `ACL_VIS_PUBLIC` macro) has been [removed](https://github.com/zotonic/zotonic/pull/1408) on master.

**Comment by caiodark** [comment]
Yep, I was trying with master. I have some old sites I wish I could run on newer version of zotonic they still use mod_acl_adminonly or mod_acl_simple_roles. Without those models I cannot logon on admin panel. I read that these modules should be moved on zmr soon, but they aren't there yet. I've also read that it should be possible to clone them on user/modules and then recompile zotonic to use them, the results are above. Is there any way to move a site built on 0.13 to use the current zotonic master?

**Comment by ddeboer** [comment]
> Is there any way to move a site built on 0.13 to use the current zotonic master?

There is indeed: please read the [Upgrading chapter](http://docs.zotonic.com/en/latest/developer-guide/upgrading.html#upgrading-from-0-x-to-1-0) in our documentation. It will involve switching to the mod_acl_user_groups module, which replaces all previous ACL modules.

**Comment by caiodark** [comment]
Ok. This closes the issue then.
